### ISSUE TITLE
Enable GPUs for the minikube docker driver

### ISSUE THREAD

**Issue by timoangerer** [scott-the-programmer/terraform-provider-minikube#135]
I'd like to enable NVIDIA GPUs for the docker minikube driver.

This should be possible by using the `--gpus all` flag, according to the [official minikube docs](https://minikube.sigs.k8s.io/docs/tutorials/nvidia/#using-the-docker-driver):
`minikube start --driver docker --container-runtime docker --gpus all`

I can't find how to do this using the terraform provider.

**Comment by caerulescens** [comment]
@timoangerer This has been on my todo list, but I'm going to use the `kvm2` driver which requires two graphics cards available on the host; I'm going to get around to it _soon_, but there are a number of things that @scott-the-programmer is fixing with respect to `terraform-provider-minikube`, and it wouldn't be surprising if this doesn't work yet as I don't think anyhow has tried (I haven't). 

Since `terraform-provider-minikube` is a wrapper to `minikube`, this should be a lot easier to fix than you initially may think. Could you please provide more debugging information so this work can be prioritized?

**Comment by timoangerer** [comment]
Is there a possibility to just forward the `--gpus all` flag to minikube? Maybe some generic key value map that gets pass on directly?

**Comment by timoangerer** [comment]
I'm honestly not sure what the `--gpus all` does. I know that it installs the `nvidia-device-plugin` in the cluster and setups up so that it's working correctly.

When create a cluster using the terraform provider and try to manually install the `nvidia-device-plugin`, the plugin fails. So it seems like the flag has to be present during minikube cluster creation to properly support GPUs.

**Comment by caerulescens** [comment]
@timoangerer 

> Is there a possibility to just forward the --gpus all flag to minikube? Maybe some generic key value map that gets pass on directly?

Yes, but it looks like the usage has not documented for `terraform-provider-minikube`.

---

@scott-the-programmer 

Looks like it's missing [here](https://registry.terraform.io/providers/scott-the-programmer/minikube/latest/docs/resources/cluster), but it shows in the [`minikube start` docs](https://minikube.sigs.k8s.io/docs/commands/start/):

```
...
-g, --gpus string                       Allow pods to use your NVIDIA GPUs. Options include: [all,nvidia] (Docker driver with Docker container-runtime only)
...
```

**Comment by scott-the-programmer** [comment]
Ah interesting - i think it's the schema generator that is silently ignoring the --gpu flag (probably because it is the only one formatted like `-g, --gpu...`)

Should be an easy fix 👍🏽
