### ISSUE TITLE
Terrform deployment stops working if enabling additional addons

### ISSUE THREAD

**Issue by kwallner** [scott-the-programmer/terraform-provider-minikube#53]
Issue came up as tried to enable minikube addons `storage-provisioner` and/or `csi-hostpath-driver`.

Could reproduce issue with  `examples/resources/minikube_cluster`.

#### Setup:
* Using `examples/resources/minikube_cluster` with following modifications:
    * Disabled (commented out) `resource "minikube_cluster" "hyperkit" [...]`
    * Renamed cluster: `cluster_name = "minikube"` ... maybe does not matter, but for completeness
* Using terraform-provider-minikube `version = "0.2.1"` (also used `0.2.0`) 

#### Tests:
* Was using addon `storage-provisioner` (also applies to at least `csi-hostpath-driver`)

##### Manually enabling addon

1. Apply: `terraform apply` without errors/warnings 
2. Add Addon: `minikube addons enable storage-provisioner` without errors/warnings 
3. Run apply again: `terraform apply`

Step `3.` fails with:
```
minikube_cluster.docker: Refreshing state... [id=minikube]
kubernetes_deployment.deployment: Refreshing state... [id=default/nginx-example]
╷
│ Error: Get "http://localhost/apis/apps/v1/namespaces/default/deployments/nginx-example": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with kubernetes_deployment.deployment,
│   on resource.tf line 37, in resource "kubernetes_deployment" "deployment":
│   37: resource "kubernetes_deployment" "deployment" {
│ 
```
`minkube status` still states everything is ok.

##### Adding addon `storage-provisioner`  to `addons` for `resource "minikube_cluster" "docker"` 

1. Apply: `terraform apply` without errors/warnings 
2. Run apply again: `terraform apply`

Step `2.` fails with `connection refused` same as above. 

For completeness: without the additional addons the are no issues/problems.

Thank you for your great work. It really helps with k8s-learning, -experiments and -testing.

**Comment by scott-the-programmer** [comment]
Thanks for bringing this up!

The root cause actually stems from dependencies between providers, where the cluster is evaluated to be recreated, but the kubernetes provider still has a dependency on it - here's a much better [explanation of the problem](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1307#issuecomment-873089000)

However, the minikube provider naively tries to recreate the cluster whenever [addons is modified](https://github.com/scott-the-programmer/terraform-provider-minikube/blob/a95f96ab2a4fb9c50f331609bf8eaa8d1152df52/minikube/schema_cluster.go#L63) which i don't think is quite right. I'll look into making a simple update, similar to how 'minikube addons enable... ` works! 

Thanks again!

**Comment by kwallner** [comment]
Does this explain 2nd case "Adding addon storage-provisioner to addons [...]" (see above), when the addons are already initially defined?

**Comment by scott-the-programmer** [comment]
> Does this explain 2nd case "Adding addon storage-provisioner to addons [...]" (see above), when the addons are already initially defined?

I believe so, yes. You can try `terraform apply -refresh=false` to confirm whether or not it's the addon property triggering the recreate

**Comment by kwallner** [comment]
> I believe so, yes. You can try terraform apply -refresh=false to confirm whether or not it's the addon property triggering the recreate

Confirm.

#54 looks promising. 

I'll be not available for feedback within next 3 weeks, so closing this issue.
