### ISSUE TITLE
Storage provisioner seems to get enabled but doesn't provision storage in apply

### ISSUE THREAD

**Issue by sohaib94** [scott-the-programmer/terraform-provider-minikube#71]
Storage provisioner seems to get enabled now after the previous issue but when applied with a pvc afterwards, the pvc is stuck in a pending state. 

Example tf:
```
resource "minikube_cluster" "docker" {
  cluster_name = "${var.prefix}minikube"

  driver              = "docker"
  auto_update_drivers = true
  container_runtime   = "docker"

  cpus   = 4
  memory = "16384mb"

  cni = "calico"

  wait = ["all"]

  addons = [
    "dashboard",
    "default-storageclass",
    "storage-provisioner",
    "ingress",
    "ingress-dns",
    "istio",
    "istio-provisioner",
    "logviewer",
    "metrics-server"
  ]
}
resource "kubernetes_namespace" "ns" {
  metadata {
    name = "${var.prefix}backstage"
  }
}
resource "kubernetes_persistent_volume_claim" "pg_pvc" {
  metadata {
    name      = "${var.prefix}postgres"
    namespace = local.namespace
    labels = {
      type = "local"
    }
  }
  spec {
    storage_class_name = "standard"
    access_modes = [
      "ReadWriteOnce"
    ]
    resources {
      requests = {
        storage = "2G"
      }
    }
  }
}
```

Same as before though, this does work if you add the provisioner at the end and `local-exec` with minikube cli to enable the `storage-provisioner`

**Comment by scott-the-programmer** [comment]
Thanks for trying the latest version out! While the last fix did remedy part of the problem, it turns out that the storage provisioner version is actually supposed to be [embedded during the build](https://github.com/kubernetes/minikube/blob/40e86860211a515d2801a08d269b970b3cac232e/pkg/version/version.go#LL37C1-L38C1). 

This fix should set the storage-provisioner version such that the addon is enabled correctly when the cluster is spun up https://github.com/scott-the-programmer/terraform-provider-minikube/pull/72

I was able to reproduce it and verify the fix locally with your config 😄 

<img width="705" alt="image" src="https://github.com/scott-the-programmer/terraform-provider-minikube/assets/19235440/ac98f3c5-4d61-4149-b416-9319847495d5">

I'll merge this PR in and cut a new release shortly 🎉 

Thanks again!
